### ISSUE TITLE
Only first commend shown for github issues

### ISSUE THREAD

**Issue by jotsetung** [arbox/org-sync#19]
Hi there!
For the github backend only the first comment is shown for an issue; is there a way to get all comments for an issue?

**Comment by plajjan** [comment]
org-sync doesn't fetch comments at all. By "first comment" I think you actually mean the issue description, right?

**Comment by jotsetung** [comment]
Yes correct @plajjan

**Comment by plajjan** [comment]
Right, so this is simply not implemented. I added #35 to track the addition of this feature, feel free to comment there :) Closing this issue.
