### ISSUE TITLE
Evernote backend

### ISSUE THREAD

**Issue by timoc** [arbox/org-sync#21]
Being able to sync with evernote would be very handy.

**Comment by arbox** [comment]
Thank you for your request!
I'm not an Evernote user, so I will need help on this issue. Even if in form of the protocol specification.

**Comment by timoc** [comment]
You can get an evernote account for free ( i can send you a link). I use it for capture on my android phone, while away from my desktop. I'm more interested in 'reading' 

Here is an example of an evernote mode:
https://github.com/pymander/evernote-mode

**Comment by plajjan** [comment]
I'm closing this because I have no interest in implementing this and it probably takes quite a bit of effort. In particular as Evernote isn't a typical issue/bug tracker. Unless someone wants to spend the time to do this it's not going to happen. We can revive it if someone is interested.
