### ISSUE TITLE
Cant get org-sync to create Issues

### ISSUE THREAD

**Issue by discipolo** [arbox/org-sync#22]
Pulling works fine, is anyone successfully creating issues using this?

**Comment by TobiMarg** [comment]
I just tried it with the test repo from the readme and it worked fine. (I just couldn't close the issues)

**Comment by michaelplews** [comment]
I am also having this issue, seems that the test repo works fine, however the following error shows:
 ```
Buglist "Issues of <REPO>" contains unmerged bugs.
```

I managed to track the issue to being whether you have an underscore in the comments of the new issue. This seems to be related to issue #25.

**Comment by arbox** [comment]
We'll look at it! Thank you for reporting!

**Comment by yisraeldov** [comment]
This happens when you have more than one TODO that is not yet synced.  I fixed it and am sending a pull request

**Comment by yisraeldov** [comment]
@michaelplews pull request #33 should fix your issue

**Comment by michaelplews** [comment]
Amazing! Thanks!

**Comment by yisraeldov** [comment]
Let's see if the report owner can do the merge

**Comment by plajjan** [comment]
There seems to be two things going on here
 * multiple new issues, which is fixed through #34 (that merges in the fix @yisraeldov wrote in #33 )
 * issues with underscore in the name, which we track in #25 

Thus, nothing left to track in this issue as far as I can see - closing.
