### ISSUE TITLE
Trying to close issue creates a new one (github)

### ISSUE THREAD

**Issue by TobiMarg** [arbox/org-sync#23]
Following the readme, I tried creating a test issue on [arbox/org-sync-test](https://github.com/arbox/org-sync-test/issues) which worked.
Trying to close the issue and sync again resulted in another copy of the same issue being created (without closing the first).

**Comment by arbox** [comment]
We'll look at this issue, thank you for reporting!

**Comment by jgkamat** [comment]
I can reproduce this as well. A workaround to this issue is to remove the CLOSED timestampt that is added when you close an issue in org mode, before running a sync. Hopefully that's enough to help pin the source down!

**Comment by plajjan** [comment]
Right, it seems that the `:PROPERTIES:` drawer needs to be right under the issue title, if not, org-sync won't recognize it properly and assume it's a new issue (because it fails to find the `id` attribute, that is in the drawer).

**Comment by arbox** [comment]
@plajjan really happy to see you working on the project. I'm lacking time for that. Thank you for your time and work!

**Comment by plajjan** [comment]
So this should be fixed with #37. Closing.

**Comment by plajjan** [comment]
buuut, it doesn't work :/ I can still reproduce the issue. As soon as the CLOSED timestamp is there, a new issue is created instead of closing the existing one. Reopening. I was pretty sure I had this nailed down with #37. Oh well.

**Comment by plajjan** [comment]
Haha, okay really, it is fixed. I just had to many remotes and didn't properly sync up changes from master on my branches where I tested this. Now that I'm sure I got the right commit from #37 I do see it is fixed. Phew.
