### ISSUE TITLE
not working with redmine?

### ISSUE THREAD

**Issue by Hans-Maulwurf** [arbox/org-sync#28]
Hello,
last commit seems to be a few days ago. May it be that org-sync is not working anymore with redmine? 
When I just org-sync-import and insert the url of a redmine-project, I only get the header "issues of project #66" and 3 lines of properties (properties, url, end).

**Comment by arbox** [comment]
Hello,
I'm not using org-sync for Redmine, initially it was intended to function with Redmine as well. Could you please elaborate on your problems?

**Comment by plajjan** [comment]
I'm going to close this due to inactivity. There's nothing really concrete to go on here so without further information it's impossible to do anything. Feel free to re-open or open new issue though :)
