### ISSUE TITLE
bitbucket, when importing only the issues but no comments are imported

### ISSUE THREAD

**Issue by ouboub** [arbox/org-sync#30]
I just realized, that importing my BB repo's issue, only imported the issues but not its comments.

regards

Uwe Brauer

**Comment by yisraeldov** [comment]
Do any  of the backends import comments?

**Comment by ouboub** [comment]
Which backends? can you give me an example?

**Comment by yisraeldov** [comment]
I'm saying that I don't think any of the backends import comments, it is not a feature that is supported.

**Comment by ouboub** [comment]
You mean bitbucket does not? or mercurial itself?

**Comment by yisraeldov** [comment]
Doesn't have anything to do with mercurial or bit bucket. org-sync doesn't
sync comments at all. ( as far as I know )

**Comment by plajjan** [comment]
I agree with @yisraeldov, org-sync simply does not support importing comments. There is no code for it.

**Comment by plajjan** [comment]
This is same issue as #19. It's not specific to bitbucket but is a generic lack of feature in org-sync.

**Comment by plajjan** [comment]
I opened #35, i.e. this is a new feature. I tried to describe what needs to be implemented. Please go there and comment :) I'm closing this issue.
