### ISSUE TITLE
Missing omd-mutate-doc-list definition

### ISSUE THREAD

**Issue by syohex** [arbox/org-sync#8]
https://github.com/arbox/org-sync/blob/master/omd.el#L172

I got following error when byte-compiling omd.el.

```
In end of data:
omd.el:222:1:Warning: the function `omd-mutate-doc-list' is not known to be
    defined.
```

**Comment by ardumont** [comment]
Hello,

`omd.el` seems not to be used in any other namespaces but `omd.el`.
So i believe, it's a utility namespace for manual testing.

So could be low priority.

My maybe irrelevant 2 cents :D 

Cheers,

**Comment by aaptel** [comment]
`omd.el` was something I made to test the /other/ org-mode GSoC project and has nothing to do with org-sync. You can completely remove it.
